-- ============================================
-- PREGUNTAS SOBRE CONSTITUCIÓN ESPAÑOLA
-- Artículos 4 al 9
-- Total: 54 preguntas (9 por artículo × 6 artículos)
-- ============================================
-- IDs de la base de datos:
-- LEY_ID: 2 (Constitución Española de 1978)
-- TEMA_ID: 2 (Tema 1 - La Constitución española de 1978)
-- ARTICULO_4_ID: 93
-- ARTICULO_5_ID: 94
-- ARTICULO_6_ID: 95
-- ARTICULO_7_ID: 96
-- ARTICULO_8_ID: 97
-- ARTICULO_9_ID: 7
-- ============================================

-- ============================================
-- ARTÍCULO 4 - LA BANDERA DE ESPAÑA
-- ============================================

-- PREGUNTAS FÁCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('Según el artículo 4 de la Constitución Española, ¿cuáles son los colores de la bandera de España?', 'facil', '**Correcto.** El artículo 4.1 CE establece que la bandera de España está formada por tres franjas horizontales: roja, amarilla y roja, siendo la amarilla de doble anchura que cada una de las rojas. Esta disposición es fundamental para la identidad nacional.', 'Roja, amarilla y roja', 'Roja, amarilla, azul y roja', 'Amarilla, roja y amarilla', 'Roja, blanca y roja', 'A', 1, 2, 2, 93),
('El artículo 4 de la Constitución Española regula:', 'facil', '**Correcto.** El artículo 4 CE se dedica íntegramente a la regulación de la bandera de España y las banderas de las Comunidades Autónomas, estableciendo sus características y uso.', 'El himno nacional', 'La bandera de España', 'El escudo nacional', 'La capital del Estado', 'B', 1, 2, 2, 93),
('¿Qué establece el artículo 4.1 de la Constitución Española sobre la bandera?', 'facil', '**Correcto.** El artículo 4.1 CE establece que la bandera de España está formada por tres franjas horizontales, roja, amarilla y roja, siendo la amarilla de doble anchura que cada una de las rojas.', 'Que tiene cuatro franjas', 'Que tiene tres franjas horizontales: roja, amarilla y roja, siendo la amarilla de doble anchura', 'Que tiene dos franjas verticales', 'Que tiene cinco franjas', 'B', 1, 2, 2, 93);

-- PREGUNTAS MODERADAS (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('Según el artículo 4.2 de la Constitución Española, los estatutos de las Comunidades Autónomas:', 'moderada', '**Correcto.** El artículo 4.2 CE establece que los estatutos podrán reconocer banderas y enseñas propias de las Comunidades Autónomas. Estas se utilizarán junto a la bandera de España en sus edificios públicos y en sus actos oficiales.', 'No pueden reconocer banderas propias', 'Pueden reconocer banderas y enseñas propias que se utilizarán junto a la bandera de España', 'Deben usar exclusivamente la bandera de España', 'Pueden sustituir la bandera de España', 'B', 1, 2, 2, 93),
('El artículo 4.2 de la Constitución Española establece que las banderas de las Comunidades Autónomas se utilizarán:', 'moderada', '**Correcto.** El artículo 4.2 CE establece que las banderas y enseñas propias de las Comunidades Autónomas se utilizarán junto a la bandera de España en sus edificios públicos y en sus actos oficiales, reflejando el equilibrio entre unidad y diversidad.', 'Solo en actos privados', 'Junto a la bandera de España en sus edificios públicos y en sus actos oficiales', 'En lugar de la bandera de España', 'Solo en el territorio de la Comunidad', 'B', 1, 2, 2, 93),
('¿Qué característica específica tiene la franja amarilla de la bandera de España según el artículo 4.1 CE?', 'moderada', '**Correcto.** El artículo 4.1 CE establece expresamente que la franja amarilla tiene doble anchura que cada una de las franjas rojas, lo que le confiere su característica proporción distintiva.', 'Tiene la misma anchura que las rojas', 'Tiene doble anchura que cada una de las rojas', 'Tiene triple anchura que las rojas', 'Tiene la mitad de anchura que las rojas', 'B', 1, 2, 2, 93);

-- PREGUNTAS DIFÍCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('El reconocimiento de banderas propias por los estatutos de las Comunidades Autónomas según el artículo 4.2 CE:', 'dificil', '**Correcto.** El artículo 4.2 CE establece que los estatutos **podrán** reconocer banderas propias, lo que implica que es una facultad discrecional, no una obligación. Además, siempre deben utilizarse junto a la bandera de España, nunca en sustitución.', 'Es obligatorio para todas las Comunidades', 'Es una facultad discrecional que pueden ejercer los estatutos', 'Está prohibido por la Constitución', 'Solo es posible mediante ley orgánica', 'B', 1, 2, 2, 93),
('La regulación constitucional de la bandera en el artículo 4 CE tiene como fundamento:', 'dificil', '**Correcto.** El artículo 4 CE regula la bandera como símbolo de la unidad nacional y la identidad del Estado español, estableciendo un equilibrio entre la unidad representada por la bandera nacional y la diversidad territorial reconocida mediante las banderas autonómicas.', 'Solo la unidad nacional', 'La unidad nacional y el reconocimiento de la diversidad territorial', 'La supremacía del Estado central', 'La independencia de las Comunidades Autónomas', 'B', 1, 2, 2, 93),
('Según el artículo 4.2 CE, el uso de las banderas autonómicas junto a la bandera de España es:', 'dificil', '**Correcto.** El artículo 4.2 CE establece que las banderas autonómicas se utilizarán **junto a** la bandera de España en edificios públicos y actos oficiales, lo que implica un uso simultáneo y complementario, nunca sustitutivo.', 'Opcional y discrecional', 'Obligatorio en todos los casos cuando existan banderas autonómicas', 'Prohibido en actos oficiales', 'Solo permitido en el territorio de la Comunidad', 'B', 1, 2, 2, 93);

-- ============================================
-- ARTÍCULO 5 - LA CAPITAL DEL ESTADO
-- ============================================

-- PREGUNTAS FÁCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('De acuerdo con el artículo 5 de la Constitución Española, ¿cuál es la capital del Estado?', 'facil', '**Correcto.** El artículo 5 CE establece de forma expresa que la capital del Estado es la villa de Madrid. Esta disposición tiene carácter constitucional y no puede ser modificada por ley ordinaria.', 'Barcelona', 'Madrid', 'Sevilla', 'Valencia', 'B', 1, 2, 2, 94),
('El artículo 5 de la Constitución Española establece que la capital del Estado es:', 'facil', '**Correcto.** El artículo 5 CE establece expresamente que la capital del Estado es la villa de Madrid, utilizando la denominación tradicional de "villa".', 'La ciudad de Madrid', 'La villa de Madrid', 'El municipio de Madrid', 'La Comunidad de Madrid', 'B', 1, 2, 2, 94),
('¿Qué regula el artículo 5 de la Constitución Española?', 'facil', '**Correcto.** El artículo 5 CE se dedica exclusivamente a establecer la capital del Estado, que es la villa de Madrid.', 'La organización territorial', 'La capital del Estado', 'Las Comunidades Autónomas', 'Los símbolos del Estado', 'B', 1, 2, 2, 94);

-- PREGUNTAS MODERADAS (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('La determinación de la capital del Estado en el artículo 5 CE tiene carácter:', 'moderada', '**Correcto.** El artículo 5 CE tiene carácter constitucional, lo que significa que la capital del Estado no puede ser modificada mediante ley ordinaria, sino que requeriría una reforma constitucional.', 'Reglamentario', 'Constitucional', 'Legal ordinario', 'Administrativo', 'B', 1, 2, 2, 94),
('El artículo 5 de la Constitución Española utiliza la expresión:', 'moderada', '**Correcto.** El artículo 5 CE utiliza la expresión tradicional "villa de Madrid" para referirse a la capital del Estado, manteniendo la denominación histórica.', '"Ciudad de Madrid"', '"Villa de Madrid"', '"Municipio de Madrid"', '"Comunidad de Madrid"', 'B', 1, 2, 2, 94),
('Para modificar la capital del Estado establecida en el artículo 5 CE sería necesario:', 'moderada', '**Correcto.** Al estar establecida en la Constitución, la capital del Estado solo puede modificarse mediante el procedimiento de reforma constitucional establecido en el Título X de la CE.', 'Una ley ordinaria', 'Un Real Decreto', 'Una reforma constitucional', 'Un acuerdo del Gobierno', 'C', 1, 2, 2, 94);

-- PREGUNTAS DIFÍCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('La regulación de la capital del Estado en el artículo 5 CE tiene como finalidad:', 'dificil', '**Correcto.** El artículo 5 CE establece la capital del Estado para garantizar la estabilidad y permanencia de la sede de los órganos constitucionales y del Gobierno, evitando la discrecionalidad en su determinación.', 'Establecer la sede del Tribunal Constitucional', 'Garantizar la estabilidad y permanencia de la sede de los órganos constitucionales', 'Regular la organización administrativa de Madrid', 'Establecer competencias de la Comunidad de Madrid', 'B', 1, 2, 2, 94),
('El artículo 5 CE establece la capital del Estado en el contexto de:', 'dificil', '**Correcto.** El artículo 5 CE se encuentra en el Título Preliminar, que establece los principios fundamentales del Estado, entre los que se incluye la determinación de la capital como elemento básico de la organización estatal.', 'La organización territorial del Estado', 'Los principios fundamentales del Estado en el Título Preliminar', 'Las competencias del Estado', 'La organización de las Comunidades Autónomas', 'B', 1, 2, 2, 94),
('La expresión "villa de Madrid" en el artículo 5 CE:', 'dificil', '**Correcto.** La expresión "villa de Madrid" en el artículo 5 CE hace referencia al municipio de Madrid, manteniendo la denominación tradicional histórica, aunque actualmente Madrid tenga el rango de ciudad.', 'Se refiere solo al casco histórico', 'Hace referencia al municipio de Madrid, manteniendo la denominación tradicional', 'Está obsoleta y debe actualizarse', 'Se refiere a la Comunidad Autónoma', 'B', 1, 2, 2, 94);

-- ============================================
-- ARTÍCULO 6 - LOS PARTIDOS POLÍTICOS
-- ============================================

-- PREGUNTAS FÁCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('El artículo 6 de la Constitución Española regula:', 'facil', '**Correcto.** El artículo 6 CE se refiere expresamente a los partidos políticos, estableciendo que expresan el pluralismo político, concurren a la formación y manifestación de la voluntad popular y son instrumento fundamental para la participación política.', 'Los sindicatos', 'Los partidos políticos', 'Las Fuerzas Armadas', 'Los poderes públicos', 'B', 1, 2, 2, 95),
('Según el artículo 6 CE, los partidos políticos:', 'facil', '**Correcto.** El artículo 6 CE establece que los partidos políticos expresan el pluralismo político, concurren a la formación y manifestación de la voluntad popular y son instrumento fundamental para la participación política.', 'Están prohibidos', 'Expresan el pluralismo político y son instrumento fundamental para la participación', 'Solo pueden actuar en elecciones', 'Están subvencionados obligatoriamente', 'B', 1, 2, 2, 95),
('El artículo 6.1 de la Constitución Española establece que los partidos políticos:', 'facil', '**Correcto.** El artículo 6.1 CE establece que los partidos políticos expresan el pluralismo político, concurren a la formación y manifestación de la voluntad popular y son instrumento fundamental para la participación política.', 'Deben estar registrados obligatoriamente', 'Expresan el pluralismo político y concurren a la formación de la voluntad popular', 'Tienen carácter público', 'Están financiados exclusivamente por el Estado', 'B', 1, 2, 2, 95);

-- PREGUNTAS MODERADAS (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('El artículo 6.2 de la Constitución Española establece que la estructura interna y el funcionamiento de los partidos políticos:', 'moderada', '**Correcto.** El artículo 6.2 CE establece que la estructura interna y el funcionamiento de los partidos políticos deben ser democráticos, garantizando así la participación interna de sus miembros.', 'Deben ser secretos', 'Deben ser democráticos', 'Deben ser autoritarios', 'No están regulados', 'B', 1, 2, 2, 95),
('Según el artículo 6.2 CE, los partidos políticos deben tener estructura y funcionamiento:', 'moderada', '**Correcto.** El artículo 6.2 CE exige que la estructura interna y el funcionamiento de los partidos políticos sean democráticos, lo que implica transparencia, participación de los afiliados y respeto a los derechos fundamentales.', 'Jerárquicos', 'Democráticos', 'Centralizados', 'Descentralizados', 'B', 1, 2, 2, 95),
('El artículo 6 CE establece que los partidos políticos son instrumento fundamental para:', 'moderada', '**Correcto.** El artículo 6 CE establece que los partidos políticos son instrumento fundamental para la participación política, reconociendo su papel esencial en el sistema democrático.', 'La organización económica', 'La participación política', 'La administración de justicia', 'La defensa nacional', 'B', 1, 2, 2, 95);

-- PREGUNTAS DIFÍCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('La creación y el ejercicio de la actividad de los partidos políticos según el artículo 6 CE:', 'dificil', '**Correcto.** El artículo 6 CE establece que la creación y el ejercicio de la actividad de los partidos políticos son libres dentro del respeto a la Constitución y a la ley, lo que implica libertad de creación pero con límites constitucionales y legales.', 'Están sujetos a autorización previa', 'Son libres dentro del respeto a la Constitución y a la ley', 'Requieren registro obligatorio en todos los casos', 'Están prohibidos fuera del ámbito electoral', 'B', 1, 2, 2, 95),
('El artículo 6 CE establece que los partidos políticos concurren a:', 'dificil', '**Correcto.** El artículo 6 CE establece que los partidos políticos concurren a la formación y manifestación de la voluntad popular, reconociendo su función esencial en el proceso democrático de expresión de la soberanía nacional.', 'La organización del Estado', 'La formación y manifestación de la voluntad popular', 'La administración pública', 'La defensa del territorio', 'B', 1, 2, 2, 95),
('La regulación de los partidos políticos en el artículo 6 CE se fundamenta en:', 'dificil', '**Correcto.** El artículo 6 CE regula los partidos políticos como expresión del pluralismo político y como instrumento de participación, fundamentándose en los principios democráticos y en el reconocimiento del pluralismo como valor constitucional.', 'El principio de unidad política', 'El pluralismo político y la participación democrática', 'La centralización del poder', 'La uniformidad ideológica', 'B', 1, 2, 2, 95);

-- ============================================
-- ARTÍCULO 7 - SINDICATOS Y ASOCIACIONES EMPRESARIALES
-- ============================================

-- PREGUNTAS FÁCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('El artículo 7 de la Constitución Española regula:', 'facil', '**Correcto.** El artículo 7 CE se refiere a los sindicatos de trabajadores y a las asociaciones empresariales, estableciendo su función en la defensa y promoción de los intereses económicos y sociales.', 'Los partidos políticos', 'Los sindicatos de trabajadores y las asociaciones empresariales', 'Las Fuerzas Armadas', 'Los poderes públicos', 'B', 1, 2, 2, 96),
('Según el artículo 7 CE, los sindicatos y las asociaciones empresariales:', 'facil', '**Correcto.** El artículo 7 CE establece que los sindicatos y las asociaciones empresariales contribuyen a la defensa y promoción de los intereses económicos y sociales que les son propios.', 'Están prohibidos', 'Contribuyen a la defensa y promoción de los intereses económicos y sociales', 'Solo pueden actuar en el sector privado', 'Están subvencionados obligatoriamente', 'B', 1, 2, 2, 96),
('El artículo 7 de la Constitución Española establece que los sindicatos y asociaciones empresariales contribuyen a:', 'facil', '**Correcto.** El artículo 7 CE establece que los sindicatos y las asociaciones empresariales contribuyen a la defensa y promoción de los intereses económicos y sociales que les son propios.', 'La organización política', 'La defensa y promoción de los intereses económicos y sociales', 'La administración de justicia', 'La defensa nacional', 'B', 1, 2, 2, 96);

-- PREGUNTAS MODERADAS (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('Según el artículo 7 de la Constitución Española, los sindicatos y las asociaciones empresariales:', 'moderada', '**Correcto.** El artículo 7 CE establece que los sindicatos y las asociaciones empresariales contribuyen a la defensa y promoción de los intereses económicos y sociales que les son propios. Su creación y el ejercicio de su actividad son libres dentro del respeto a la Constitución y a la ley.', 'Deben estar adscritos al Estado', 'Su creación y ejercicio de actividad son libres dentro del respeto a la Constitución y a la ley', 'Están prohibidos en el sector público', 'Solo pueden actuar en el ámbito laboral', 'B', 1, 2, 2, 96),
('El artículo 7 CE establece que la creación de sindicatos y asociaciones empresariales:', 'moderada', '**Correcto.** El artículo 7 CE establece que la creación y el ejercicio de la actividad de los sindicatos y asociaciones empresariales son libres dentro del respeto a la Constitución y a la ley.', 'Requiere autorización administrativa', 'Es libre dentro del respeto a la Constitución y a la ley', 'Está sujeta a registro obligatorio', 'Requiere aprobación gubernamental', 'B', 1, 2, 2, 96),
('Los intereses que defienden los sindicatos y asociaciones empresariales según el artículo 7 CE son:', 'moderada', '**Correcto.** El artículo 7 CE establece que los sindicatos y las asociaciones empresariales contribuyen a la defensa y promoción de los intereses económicos y sociales **que les son propios**, es decir, los específicos de cada uno.', 'Los mismos para ambos', 'Los intereses económicos y sociales que les son propios', 'Solo los intereses económicos', 'Solo los intereses sociales', 'B', 1, 2, 2, 96);

-- PREGUNTAS DIFÍCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('La libertad de creación de sindicatos y asociaciones empresariales en el artículo 7 CE:', 'dificil', '**Correcto.** El artículo 7 CE establece que la creación y el ejercicio de la actividad son libres dentro del respeto a la Constitución y a la ley, lo que implica que la libertad tiene límites constitucionales y legales, no es absoluta.', 'Es absoluta sin límites', 'Es libre dentro del respeto a la Constitución y a la ley', 'Requiere autorización previa', 'Está sujeta a condiciones económicas', 'B', 1, 2, 2, 96),
('El artículo 7 CE regula los sindicatos y asociaciones empresariales en el contexto de:', 'dificil', '**Correcto.** El artículo 7 CE se encuentra en el Título Preliminar junto con otros artículos que regulan elementos fundamentales del sistema político y social, como los partidos políticos (art. 6) y las Fuerzas Armadas (art. 8).', 'La organización económica del Estado', 'Los principios fundamentales del ordenamiento constitucional', 'Las competencias del Estado', 'La organización territorial', 'B', 1, 2, 2, 96),
('La función constitucional de los sindicatos y asociaciones empresariales según el artículo 7 CE se relaciona con:', 'dificil', '**Correcto.** El artículo 7 CE establece que los sindicatos y asociaciones empresariales contribuyen a la defensa y promoción de intereses económicos y sociales, lo que se relaciona con el derecho fundamental de libertad sindical reconocido en el artículo 28.1 CE.', 'El derecho de asociación en general', 'El derecho fundamental de libertad sindical y la participación social', 'Solo el derecho de huelga', 'Exclusivamente la negociación colectiva', 'B', 1, 2, 2, 96);

-- ============================================
-- ARTÍCULO 8 - LAS FUERZAS ARMADAS
-- ============================================

-- PREGUNTAS FÁCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('El artículo 8 de la Constitución Española regula:', 'facil', '**Correcto.** El artículo 8 CE se dedica íntegramente a la regulación de las Fuerzas Armadas, estableciendo su composición, misión y principios de organización.', 'Los partidos políticos', 'Las Fuerzas Armadas', 'Los sindicatos', 'Los poderes públicos', 'B', 1, 2, 2, 97),
('Según el artículo 8.1 CE, las Fuerzas Armadas están constituidas por:', 'facil', '**Correcto.** El artículo 8.1 CE establece que las Fuerzas Armadas, constituidas por el Ejército de Tierra, la Armada y el Ejército del Aire, tienen como misión garantizar la soberanía e independencia de España.', 'Ejército de Tierra y Armada', 'Ejército de Tierra, Armada y Ejército del Aire', 'Ejército de Tierra y Guardia Civil', 'Armada y Ejército del Aire', 'B', 1, 2, 2, 97),
('El artículo 8.1 de la Constitución Española establece que las Fuerzas Armadas tienen como misión:', 'facil', '**Correcto.** El artículo 8.1 CE establece que las Fuerzas Armadas tienen como misión garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional.', 'Gestionar la seguridad ciudadana', 'Garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional', 'Administrar justicia', 'Controlar la política exterior', 'B', 1, 2, 2, 97);

-- PREGUNTAS MODERADAS (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('El artículo 8.2 de la Constitución Española establece que la estructura orgánica de las Fuerzas Armadas se regulará por:', 'moderada', '**Correcto.** El artículo 8.2 CE establece que una ley orgánica regulará las bases de la organización militar conforme a los principios de la Constitución. Esta ley orgánica es la Ley Orgánica 6/1980, de 1 de julio.', 'Real Decreto', 'Ley orgánica', 'Ley ordinaria', 'Decreto-ley', 'B', 1, 2, 2, 97),
('Según el artículo 8.2 CE, la ley orgánica que regula las Fuerzas Armadas debe establecer las bases de la organización militar:', 'moderada', '**Correcto.** El artículo 8.2 CE establece que la ley orgánica regulará las bases de la organización militar **conforme a los principios de la Constitución**, lo que implica que debe respetar los valores y principios constitucionales.', 'Sin límites', 'Conforme a los principios de la Constitución', 'Según criterios exclusivamente militares', 'Sin referencia a la Constitución', 'B', 1, 2, 2, 97),
('El artículo 8 CE establece que las Fuerzas Armadas garantizan:', 'moderada', '**Correcto.** El artículo 8.1 CE establece que las Fuerzas Armadas tienen como misión garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional.', 'Solo la integridad territorial', 'La soberanía e independencia de España, la integridad territorial y el ordenamiento constitucional', 'Solo la soberanía', 'Exclusivamente el ordenamiento constitucional', 'B', 1, 2, 2, 97);

-- PREGUNTAS DIFÍCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('La misión de las Fuerzas Armadas establecida en el artículo 8.1 CE incluye la defensa del ordenamiento constitucional, lo que implica:', 'dificil', '**Correcto.** La defensa del ordenamiento constitucional por las Fuerzas Armadas implica su sujeción al poder civil y al marco constitucional, garantizando que actúen siempre dentro del respeto a la Constitución y a las decisiones de los poderes democráticos.', 'Su independencia del poder civil', 'Su sujeción al poder civil y al marco constitucional', 'Su autonomía respecto al Gobierno', 'Su subordinación solo al Rey', 'B', 1, 2, 2, 97),
('El artículo 8.2 CE establece que la ley orgánica regulará las bases de la organización militar conforme a los principios de la Constitución, lo que significa que:', 'dificil', '**Correcto.** La referencia a los principios de la Constitución en el artículo 8.2 CE implica que la organización militar debe respetar los valores superiores del ordenamiento jurídico (libertad, justicia, igualdad y pluralismo político) y los principios democráticos establecidos en el artículo 1.1 CE.', 'Debe respetar los valores superiores y principios democráticos de la Constitución', 'Puede establecer principios propios', 'No está sujeta a límites constitucionales', 'Solo debe respetar la estructura del Estado', 'A', 1, 2, 2, 97),
('La regulación de las Fuerzas Armadas en el artículo 8 CE se fundamenta en:', 'dificil', '**Correcto.** El artículo 8 CE regula las Fuerzas Armadas como garantes de la soberanía nacional, la integridad territorial y el ordenamiento constitucional, fundamentándose en el principio de que el Estado tiene el monopolio de la fuerza legítima y en la necesidad de garantizar la defensa nacional dentro del marco democrático.', 'El principio de autodefensa', 'El monopolio estatal de la fuerza legítima y la defensa nacional en el marco democrático', 'La autonomía militar', 'La independencia de las Fuerzas Armadas', 'B', 1, 2, 2, 97);

-- ============================================
-- ARTÍCULO 9 - LOS CIUDADANOS Y LOS PODERES PÚBLICOS
-- ============================================

-- PREGUNTAS FÁCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('El artículo 9 de la Constitución Española establece que los ciudadanos y los poderes públicos:', 'facil', '**Correcto.** El artículo 9.1 CE establece que los ciudadanos y los poderes públicos están sujetos a la Constitución y al resto del ordenamiento jurídico, estableciendo el principio de sujeción al Derecho.', 'Están exentos de la ley', 'Están sujetos a la Constitución y al resto del ordenamiento jurídico', 'Solo los ciudadanos están sujetos a la ley', 'Solo los poderes públicos están sujetos a la Constitución', 'B', 1, 2, 2, 7),
('El artículo 9.3 de la Constitución Española establece que la Constitución garantiza:', 'facil', '**Correcto.** El artículo 9.3 CE establece que la Constitución garantiza el principio de legalidad, la jerarquía normativa, la publicidad de las normas, la irretroactividad de las disposiciones sancionadoras no favorables, la seguridad jurídica, la responsabilidad y la interdicción de la arbitrariedad.', 'La supremacía del poder ejecutivo', 'El principio de legalidad, la jerarquía normativa, la publicidad de las normas y la seguridad jurídica', 'La inmunidad de los cargos públicos', 'La discrecionalidad administrativa ilimitada', 'B', 1, 2, 2, 7),
('Según el artículo 9 CE, los ciudadanos y los poderes públicos están sujetos a:', 'facil', '**Correcto.** El artículo 9.1 CE establece expresamente que los ciudadanos y los poderes públicos están sujetos a la Constitución y al resto del ordenamiento jurídico.', 'Solo a la Constitución', 'A la Constitución y al resto del ordenamiento jurídico', 'Solo a las leyes', 'A los reglamentos', 'B', 1, 2, 2, 7);

-- PREGUNTAS MODERADAS (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('El artículo 9.3 de la Constitución Española establece la irretroactividad de las disposiciones sancionadoras:', 'moderada', '**Correcto.** El artículo 9.3 CE establece la irretroactividad de las disposiciones sancionadoras **no favorables o restrictivas de derechos individuales**. Esto significa que solo se prohíbe la retroactividad cuando la norma es desfavorable o restringe derechos, pero sí se permite la retroactividad cuando la norma es favorable al ciudadano.', 'En todos los casos, sin excepción', 'Solo de las disposiciones no favorables o restrictivas de derechos individuales', 'Solo de las disposiciones penales', 'De ninguna disposición', 'B', 1, 2, 2, 7),
('El principio de jerarquía normativa establecido en el artículo 9.3 CE implica que:', 'moderada', '**Correcto.** El principio de jerarquía normativa establecido en el artículo 9.3 CE implica que las normas de rango inferior no pueden contradecir a las de rango superior, estableciendo un orden de prelación: Constitución, ley orgánica, ley ordinaria, reglamento.', 'Todas las normas tienen el mismo valor', 'Las normas de rango inferior no pueden contradecir a las de rango superior', 'Solo la Constitución tiene valor', 'Los reglamentos prevalecen sobre las leyes', 'B', 1, 2, 2, 7),
('El artículo 9.3 CE garantiza la publicidad de las normas, lo que significa que:', 'moderada', '**Correcto.** La publicidad de las normas garantizada en el artículo 9.3 CE implica que las normas deben ser publicadas oficialmente para que puedan ser conocidas por los ciudadanos y produzcan efectos jurídicos, garantizando así la seguridad jurídica.', 'Las normas pueden ser secretas', 'Las normas deben ser publicadas oficialmente para producir efectos', 'Solo algunas normas deben publicarse', 'La publicidad es opcional', 'B', 1, 2, 2, 7);

-- PREGUNTAS DIFÍCILES (3)
INSERT INTO pregunta (texto, dificultad, retroalimentacion, opcion_a, opcion_b, opcion_c, opcion_d, respuesta_correcta, activo, tema_id, ley_id, articulo_id) VALUES
('El artículo 9.2 CE establece que corresponde a los poderes públicos promover las condiciones para que la libertad y la igualdad del individuo y de los grupos sean reales y efectivas, lo que implica:', 'dificil', '**Correcto.** El artículo 9.2 CE establece que los poderes públicos deben promover las condiciones para que la libertad y la igualdad sean reales y efectivas, lo que implica una acción positiva de los poderes públicos para remover obstáculos y garantizar la igualdad material, no solo formal.', 'Una abstención de los poderes públicos', 'Una acción positiva de los poderes públicos para garantizar la igualdad material', 'Solo el reconocimiento formal de derechos', 'La prohibición de toda intervención pública', 'B', 1, 2, 2, 7),
('La interdicción de la arbitrariedad de los poderes públicos establecida en el artículo 9.3 CE significa que:', 'dificil', '**Correcto.** La interdicción de la arbitrariedad establecida en el artículo 9.3 CE significa que los poderes públicos deben actuar con fundamento en la ley y con razonabilidad, no pudiendo ejercer sus competencias de forma caprichosa o sin justificación jurídica adecuada.', 'Los poderes públicos pueden actuar libremente', 'Los poderes públicos deben actuar con fundamento en la ley y con razonabilidad', 'Solo el poder judicial está sujeto a límites', 'La arbitrariedad está permitida en casos excepcionales', 'B', 1, 2, 2, 7),
('El artículo 9.3 CE garantiza la seguridad jurídica, principio que se relaciona con:', 'dificil', '**Correcto.** La seguridad jurídica garantizada en el artículo 9.3 CE se relaciona con la necesidad de que los ciudadanos puedan conocer con certeza cuáles son sus derechos y obligaciones, y confiar en que las normas se aplicarán de forma previsible y estable, sin cambios retroactivos desfavorables.', 'La incertidumbre normativa', 'La certeza y previsibilidad del ordenamiento jurídico para los ciudadanos', 'La discrecionalidad administrativa', 'La modificación constante de las normas', 'B', 1, 2, 2, 7);





